/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NameOnlyMetaDataRequest } from './nameOnlyMetaDataRequest';

export class CreateWorkflowStepDefinitionRequest {
    /**
    * The number of minutes after finishing the previous step that this step should execute by.
    */
    'delay'?: number;
    /**
    * Step position
    */
    'stepPosition': number;
    /**
    * Step position
    */
    'previousStep'?: number;
    /**
    * Step position
    */
    'nextStep'?: number;
    /**
    * Max run count of a step
    */
    'maxRunCount'?: number;
    /**
    * Ports
    */
    'ports'?: object | null;
    /**
    * The port that starts this step.
    */
    'triggerPort'?: string;
    'metaData': NameOnlyMetaDataRequest;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "delay",
            "baseName": "delay",
            "type": "number"
        },
        {
            "name": "stepPosition",
            "baseName": "stepPosition",
            "type": "number"
        },
        {
            "name": "previousStep",
            "baseName": "previousStep",
            "type": "number"
        },
        {
            "name": "nextStep",
            "baseName": "nextStep",
            "type": "number"
        },
        {
            "name": "maxRunCount",
            "baseName": "maxRunCount",
            "type": "number"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "object"
        },
        {
            "name": "triggerPort",
            "baseName": "triggerPort",
            "type": "string"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "NameOnlyMetaDataRequest"
        }    ];

    static getAttributeTypeMap() {
        return CreateWorkflowStepDefinitionRequest.attributeTypeMap;
    }
}

