/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ExcludeCodeMetaDataResponse {
    /**
    * The id of the metaData.
    */
    'metaDataId': string;
    /**
    * The name of the step the metaData is linked to.
    */
    'name': string;
    /**
    * The code that will run for steps with this external name.
    */
    'code': string;
    /**
    * Object version
    */
    'versionId'?: string;
    /**
    * The description of the executable code.
    */
    'description': string;
    /**
    * Is the code public or private.
    */
    'isPublic': boolean;
    /**
    * The available ports for this step
    */
    'ports': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "metaDataId",
            "baseName": "metaDataId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "isPublic",
            "baseName": "isPublic",
            "type": "boolean"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ExcludeCodeMetaDataResponse.attributeTypeMap;
    }
}

