/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SetStepInstanceExecuteByRequestDto {
    /**
    * Date to set the executeBy to.
    */
    'executeBy': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "executeBy",
            "baseName": "executeBy",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return SetStepInstanceExecuteByRequestDto.attributeTypeMap;
    }
}

