/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkflowStepInstanceResponse } from './workflowStepInstanceResponse';

export class WorkflowInstanceResponse {
    /**
    * Workflow Instance ID
    */
    'id': string;
    /**
    * Organization ID
    */
    'orgId': string;
    /**
    * Organization ID
    */
    'siteId': string;
    /**
    * Workflow Definition ID
    */
    'workflowDefinitionId': string;
    /**
    * The ID of the event that triggered this workflow
    */
    'triggeringEventId': string;
    /**
    * The start time of this workflow
    */
    'startedAt'?: Date;
    /**
    * The start time of this workflow
    */
    'finishedAt'?: Date;
    /**
    * The status of this workflow
    */
    'workflowStatusId': number;
    /**
    * The steps of this workflow instance.
    */
    'steps': Array<WorkflowStepInstanceResponse>;
    /**
    * Data
    */
    'data': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "workflowDefinitionId",
            "baseName": "workflowDefinitionId",
            "type": "string"
        },
        {
            "name": "triggeringEventId",
            "baseName": "triggeringEventId",
            "type": "string"
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date"
        },
        {
            "name": "finishedAt",
            "baseName": "finishedAt",
            "type": "Date"
        },
        {
            "name": "workflowStatusId",
            "baseName": "workflowStatusId",
            "type": "number"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<WorkflowStepInstanceResponse>"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowInstanceResponse.attributeTypeMap;
    }
}

