/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExcludeCodeMetaData } from './excludeCodeMetaData';

export class WorkflowStepDefinitionResponse {
    /**
    * Workflow Step Definition ID
    */
    'id': string;
    /**
    * Workflow Definition ID of this step
    */
    'workflowDefinitionId': string;
    /**
    * Step position
    */
    'stepPosition': number;
    /**
    * The number of times this step can run.
    */
    'maxCount': number;
    /**
    * Ports
    */
    'ports'?: object;
    'metaData': ExcludeCodeMetaData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "workflowDefinitionId",
            "baseName": "workflowDefinitionId",
            "type": "string"
        },
        {
            "name": "stepPosition",
            "baseName": "stepPosition",
            "type": "number"
        },
        {
            "name": "maxCount",
            "baseName": "maxCount",
            "type": "number"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "object"
        },
        {
            "name": "metaData",
            "baseName": "metaData",
            "type": "ExcludeCodeMetaData"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowStepDefinitionResponse.attributeTypeMap;
    }
}

