/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WorkflowStepInstanceResponse {
    /**
    * Workflow Step Instance ID
    */
    'id': string;
    /**
    * Workflow Step Instance Description
    */
    'description': string;
    /**
    * Workflow Instance ID of this step
    */
    'workflowInstanceId': string;
    /**
    * Workflow Step Definition ID of this step
    */
    'workflowStepDefinitionId': string;
    /**
    * The start time of this workflow step
    */
    'startedAt'?: Date;
    /**
    * The start time of this workflow step
    */
    'finishedAt'?: Date;
    /**
    * The status of this workflow
    */
    'stepStatusId': number;
    /**
    * The name of a custom function.
    */
    'externalStepName'?: string;
    /**
    * Ports
    */
    'ports'?: object;
    /**
    * The port that starts this step.
    */
    'triggerPort'?: string;
    /**
    * The number of minutes after finishing the previous step that this step should execute by.
    */
    'delay'?: number;
    /**
    * The time at which this step should begin executing
    */
    'executeBy'?: Date;
    /**
    * Step position
    */
    'stepPosition': number;
    /**
    * Previous step position
    */
    'previousStep'?: number;
    /**
    * Next step position
    */
    'nextStep'?: number;
    /**
    * The number of times this step has run.
    */
    'runCount': number;
    /**
    * The number of times this step can run.
    */
    'maxRunCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "workflowInstanceId",
            "baseName": "workflowInstanceId",
            "type": "string"
        },
        {
            "name": "workflowStepDefinitionId",
            "baseName": "workflowStepDefinitionId",
            "type": "string"
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date"
        },
        {
            "name": "finishedAt",
            "baseName": "finishedAt",
            "type": "Date"
        },
        {
            "name": "stepStatusId",
            "baseName": "stepStatusId",
            "type": "number"
        },
        {
            "name": "externalStepName",
            "baseName": "externalStepName",
            "type": "string"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "object"
        },
        {
            "name": "triggerPort",
            "baseName": "triggerPort",
            "type": "string"
        },
        {
            "name": "delay",
            "baseName": "delay",
            "type": "number"
        },
        {
            "name": "executeBy",
            "baseName": "executeBy",
            "type": "Date"
        },
        {
            "name": "stepPosition",
            "baseName": "stepPosition",
            "type": "number"
        },
        {
            "name": "previousStep",
            "baseName": "previousStep",
            "type": "number"
        },
        {
            "name": "nextStep",
            "baseName": "nextStep",
            "type": "number"
        },
        {
            "name": "runCount",
            "baseName": "runCount",
            "type": "number"
        },
        {
            "name": "maxRunCount",
            "baseName": "maxRunCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowStepInstanceResponse.attributeTypeMap;
    }
}

