/**
 * ManageSpace Workflow API
 * ManageSpace Workflow API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkflowStepDefinitionResponse } from './workflowStepDefinitionResponse';

export class WorkflowDefinitionResponse {
    /**
    * Workflow definition ID
    */
    'id': string;
    /**
    * Organization ID
    */
    'orgId': string;
    /**
    * Organization ID
    */
    'siteId': string;
    /**
    * A description of what the step does.
    */
    'description': string;
    /**
    * The event that triggers this workflow.
    */
    'triggerEventSchemaCodeName': WorkflowDefinitionResponse.TriggerEventSchemaCodeNameEnum;
    /**
    * The number of instances of this definition.
    */
    'instanceCount'?: number;
    /**
    * The number of not ready instances of this definition.
    */
    'notReadyCount'?: number;
    /**
    * The number of ready instances of this definition.
    */
    'readyCount'?: number;
    /**
    * The number of in progress instances of this definition.
    */
    'inProgressCount'?: number;
    /**
    * The number of successful instances of this definition.
    */
    'successCount'?: number;
    /**
    * The number of failed instances of this definition.
    */
    'failedCount'?: number;
    /**
    * The steps of the workflow.
    */
    'steps': Array<WorkflowStepDefinitionResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "triggerEventSchemaCodeName",
            "baseName": "triggerEventSchemaCodeName",
            "type": "WorkflowDefinitionResponse.TriggerEventSchemaCodeNameEnum"
        },
        {
            "name": "instanceCount",
            "baseName": "instanceCount",
            "type": "number"
        },
        {
            "name": "notReadyCount",
            "baseName": "notReadyCount",
            "type": "number"
        },
        {
            "name": "readyCount",
            "baseName": "readyCount",
            "type": "number"
        },
        {
            "name": "inProgressCount",
            "baseName": "inProgressCount",
            "type": "number"
        },
        {
            "name": "successCount",
            "baseName": "successCount",
            "type": "number"
        },
        {
            "name": "failedCount",
            "baseName": "failedCount",
            "type": "number"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<WorkflowStepDefinitionResponse>"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowDefinitionResponse.attributeTypeMap;
    }
}

export namespace WorkflowDefinitionResponse {
    export enum TriggerEventSchemaCodeNameEnum {
        AuditEntryRequired = <any> 'AuditEntryRequired',
        MoveOutCreated = <any> 'MoveOutCreated',
        ReservationCreated = <any> 'ReservationCreated',
        ReservationUpdated = <any> 'ReservationUpdated',
        ReservationCancelled = <any> 'ReservationCancelled',
        ReservationExpired = <any> 'ReservationExpired',
        SpaceReservationCreated = <any> 'SpaceReservationCreated',
        LeaseCreated = <any> 'LeaseCreated',
        DiaryEntryRequired = <any> 'DiaryEntryRequired',
        DiaryEntryActioned = <any> 'DiaryEntryActioned',
        DocumentReady = <any> 'DocumentReady',
        DocumentRequired = <any> 'DocumentRequired',
        DocumentCompleted = <any> 'DocumentCompleted',
        CommunicationRequired = <any> 'CommunicationRequired',
        CartLeaseItemPurchased = <any> 'CartLeaseItemPurchased',
        InvoiceRequired = <any> 'InvoiceRequired',
        InvoiceV2Required = <any> 'InvoiceV2Required',
        InvoiceStateChanged = <any> 'InvoiceStateChanged',
        InvoiceV2LineItemRequired = <any> 'InvoiceV2LineItemRequired',
        ImportCompleted = <any> 'ImportCompleted',
        SmartSearchCompleted = <any> 'SmartSearchCompleted',
        PaymentRequested = <any> 'PaymentRequested',
        PaymentAttempted = <any> 'PaymentAttempted',
        UpdateUnit = <any> 'UpdateUnit'
    }
}
